import { defineField, defineType } from "sanity";

export const artwork = defineType({
  name: "artwork",
  title: "Artwork",
  type: "document",
  groups: [
    { name: "artwork", title: "Artwork & image", default: true },
    { name: "details", title: "Details" },
    { name: "placement", title: "Homepage/gallery" },
    { name: "display", title: "Display sizing" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (rule) => rule.required(),
      group: "artwork",
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
      group: "artwork",
    }),
    defineField({
      name: "image",
      title: "Main image",
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alt text",
          type: "string",
          validation: (rule) => rule.required(),
        }),
      ],
      validation: (rule) => rule.required(),
      group: "artwork",
    }),
    defineField({ name: "medium", title: "Medium", type: "string", group: "details" }),
    defineField({ name: "year", title: "Year", type: "string", group: "details" }),
    defineField({
      name: "dimensions",
      title: "Physical dimensions",
      type: "string",
      description: "Example: 18 x 24 in.",
      group: "details",
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: {
        list: ["Available", "Sold", "Private collection", "Not for sale"],
      },
      group: "details",
    }),
    defineField({ name: "category", title: "Category", type: "string", group: "details" }),
    defineField({ name: "description", title: "Description", type: "text", rows: 4, group: "details" }),
    defineField({
      name: "featured",
      title: "Featured on homepage",
      type: "boolean",
      initialValue: false,
      description: "Featured pieces can appear on the homepage and as fallback hero carousel artwork.",
      group: "placement",
    }),
    defineField({
      name: "sortOrder",
      title: "Sort order",
      type: "number",
      initialValue: 100,
      description: "Lower numbers appear earlier in the gallery.",
      group: "placement",
    }),
    defineField({
      name: "galleryDisplayWidth",
      title: "Gallery display width",
      type: "number",
      description: "Optional width in pixels for this artwork in the gallery grid. Leave blank for automatic sizing.",
      validation: (rule) => rule.min(160).max(900),
      group: "display",
    }),
    defineField({
      name: "galleryDisplayMaxHeight",
      title: "Gallery max height",
      type: "number",
      description: "Optional maximum height in pixels for this artwork in the gallery grid. Leave blank for automatic sizing.",
      validation: (rule) => rule.min(160).max(900),
      group: "display",
    }),
    defineField({
      name: "detailDisplayWidth",
      title: "Detail page display width",
      type: "number",
      description: "Optional width in pixels for this artwork on its detail page. Leave blank for automatic sizing.",
      validation: (rule) => rule.min(240).max(1400),
      group: "display",
    }),
    defineField({
      name: "detailDisplayMaxHeight",
      title: "Detail page max height",
      type: "number",
      description: "Optional maximum height in pixels for this artwork on its detail page. Leave blank for automatic sizing.",
      validation: (rule) => rule.min(240).max(1200),
      group: "display",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "medium",
      media: "image",
    },
  },
});
