import { defineField, defineType } from "sanity";

export const homePageSettings = defineType({
  name: "homePageSettings",
  title: "Homepage Settings",
  type: "document",
  groups: [
    { name: "intro", title: "Intro text", default: true },
    { name: "hero", title: "Hero carousel" },
    { name: "featured", title: "Featured work" },
  ],
  fields: [
    defineField({
      name: "eyebrowText",
      title: "Small label",
      type: "string",
      initialValue: "Artwork Portfolio",
      description: "Small uppercase label shown above the main homepage heading.",
      group: "intro",
    }),
    defineField({
      name: "headline",
      title: "Main heading",
      type: "string",
      description: "Optional. Leave blank to use the artist name from Artist Profile.",
      group: "intro",
    }),
    defineField({
      name: "intro",
      title: "Intro paragraph",
      type: "text",
      rows: 4,
      description: "Optional. Leave blank to use the artist statement from Artist Profile.",
      group: "intro",
    }),
    defineField({
      name: "introParagraphs",
      title: "Intro paragraph sections",
      type: "array",
      of: [{ type: "text", rows: 4 }],
      description: "Optional. Add multiple paragraphs when the homepage intro needs line breaks. If set, these replace the single intro paragraph above.",
      group: "intro",
    }),
    defineField({
      name: "secondaryLinkLabel",
      title: "Read more link label",
      type: "string",
      initialValue: "Read more",
      description: "Shown inline after the homepage intro text and links to the About page.",
      group: "intro",
    }),
    defineField({
      name: "showHeroArtwork",
      title: "Show hero carousel",
      type: "boolean",
      initialValue: true,
      description: "Shows selected artwork beside the homepage introduction on larger screens.",
      group: "hero",
    }),
    defineField({
      name: "heroArtworks",
      title: "Hero artworks",
      type: "array",
      of: [{ type: "reference", to: [{ type: "artwork" }] }],
      description: "Choose artworks for the homepage hero carousel. Leave blank to use featured artwork.",
      hidden: ({ parent }) => parent?.showHeroArtwork === false,
      group: "hero",
    }),
    defineField({
      name: "heroCarouselIntervalSeconds",
      title: "Hero carousel interval",
      type: "number",
      initialValue: 6,
      description: "Seconds between automatic image changes. Set to 0 to disable auto-rotation.",
      validation: (rule) => rule.min(0).max(30),
      hidden: ({ parent }) => parent?.showHeroArtwork === false,
      group: "hero",
    }),
    defineField({
      name: "showFeaturedArtwork",
      title: "Show featured artwork section",
      type: "boolean",
      initialValue: true,
      group: "featured",
    }),
    defineField({
      name: "featuredHeading",
      title: "Featured section heading",
      type: "string",
      initialValue: "Featured Work",
      hidden: ({ parent }) => parent?.showFeaturedArtwork === false,
      group: "featured",
    }),
    defineField({
      name: "featuredLinkLabel",
      title: "Gallery link label",
      type: "string",
      initialValue: "View gallery",
      description: "Shown beside the Featured Work heading and links to the Gallery page.",
      hidden: ({ parent }) => parent?.showFeaturedArtwork === false,
      group: "featured",
    }),
  ],
});
